# Generated by Django 6.1 on 2026-09-16 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='counter',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
