# Generated by Django 6.1 on 2026-08-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='counters_at_join',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
