# Generated by Django 6.1 on 2026-09-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_queueentry_counters_at_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='running_late',
            field=models.BooleanField(default=False),
        ),
    ]
