"""
Django settings for smartq project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-izvk+q(ty$(j$xj#p!yfzy2&c$y8sy0&nj7%mxi06=0j-l%edu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
     # SmartQ apps
    'accounts',
    'services',
    'queues',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'smartq.middleware.IdleRedirectMiddleware',
    ]

ROOT_URLCONF = 'smartq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'accounts.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

#Main database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smartq_db',
        'USER': 'smartq_user',
        'PASSWORD': 'your_strong_password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# TEMPORARY - MySQL mirror for ERD
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'smartq_mysql',
#        'USER': 'smartq',
#        'PASSWORD': 'SmartQ2026',
#        'HOST': '127.0.0.1',
#        'PORT': '3306',
#        'OPTIONS': {'charset': 'utf8mb4'},
#    }
#}

# SQLite backup (uncomment to roll back)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Johannesburg'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# --- Sessions & idle policy (Items 1 & 2) ---
SESSION_COOKIE_AGE = 12 * 60 * 60        # auto logout after 12 hours (Fixed math!)
IDLE_REDIRECT_SECONDS = 30 * 60          # return home after 30 min idle

# --- Email delivery: HTTPS API first (works on ALL networks), SMTP backup ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'garethzuma28@gmail.com'
EMAIL_HOST_PASSWORD = 'CHANGE_ME'   # optional backup channel (Gmail App Password)
DEFAULT_FROM_EMAIL = 'garethzuma28@gmail.com'
ADMIN_REPORT_EMAIL = 'zumagareth28@gmail.com'
# Base URL used inside email buttons (change when on hotspot)
SITE_URL = 'http://10.20.34.172:8000'

# Brevo HTTPS channel (port 443 - never blocked by campus Wi-Fi)
BREVO_API_KEY = 'CHANGE_ME'
BREVO_SENDER_EMAIL = 'garethzuma28@gmail.com'

# SmartQ login redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# --- Console logging: timestamps, colours, quiet polling ---
class _SkipPollingFilter:
    _PREFIXES = ('/notifications/api/', '/staff/api/', '/queue/api/', '/board/api/')

    def filter(self, record):
        msg = record.getMessage()
        return not (any(p in msg for p in self._PREFIXES) and '" 200 ' in msg)


class _SmartQServerFormatter(logging.Formatter):
    GREEN = '\033[32m'
    RED = '\033[31m'
    YELLOW = '\033[33m'
    RESET = '\033[0m'
    AUTH_PATHS = ('/login/', '/logout/', '/register/')

    def format(self, record):
        msg = record.getMessage()
        status = getattr(record, 'status_code', None)
        color = ''
        if status:
            if any(p in msg for p in self.AUTH_PATHS):
                color = self.GREEN          # register / login / logout → GREEN
            elif status >= 500 or status == 403:
                color = self.RED            # server errors / forbidden → red
            elif status >= 400:
                color = self.YELLOW         # not found etc → yellow
            elif status >= 300:
                color = self.GREEN          # redirects → green
        server_time = getattr(record, 'server_time', self.formatTime(record))
        line = f'[{server_time}] {msg}'
        return color + line + self.RESET if color else line


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'smartq.server': {'()': _SmartQServerFormatter},
    },
    'filters': {
        'skip_polling': {'()': _SkipPollingFilter},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'smartq.server',
            'filters': ['skip_polling'],
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}