"""
Django settings for smartq project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import logging
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------
# SECURITY
# ------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-izvk+q(ty$(j$xj#p!yfzy2&c$y8sy0&nj7%mxi06=0j-l%edu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
    'antibody-refill-jugular.ngrok-free.dev',
    '.ngrok-free.dev',
]


# ------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'corsheaders',
    'rest_framework',

    # SmartQ apps
    'accounts',
    'services',
    'queues',
]


# ------------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------------

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',              # must be FIRST
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'smartq.middleware.IdleRedirectMiddleware',
]

ROOT_URLCONF = 'smartq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'accounts.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartq.wsgi.application'


# ------------------------------------------------------------------
# SESSIONS & CACHE
# ------------------------------------------------------------------

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_SAVE_EVERY_REQUEST = True

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'smartq-session-cache',
    }
}


# ------------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smartq_db',
        'USER': 'smartq_user',
        'PASSWORD': 'your_strong_password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# TEMPORARY - MySQL mirror for ERD
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'smartq_mysql',
#         'USER': 'smartq',
#         'PASSWORD': 'SmartQ2026',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#         'OPTIONS': {'charset': 'utf8mb4'},
#     }
# }

# SQLite backup (uncomment to roll back)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# ------------------------------------------------------------------
# PASSWORD VALIDATION
# ------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ------------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Johannesburg'
USE_I18N = True
USE_TZ = True


# ------------------------------------------------------------------
# STATIC FILES
# ------------------------------------------------------------------

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'smartq_static',
]


# ------------------------------------------------------------------
# SESSIONS & IDLE POLICY
# ------------------------------------------------------------------

SESSION_COOKIE_AGE = 12 * 60 * 60        # 12 hours
IDLE_REDIRECT_SECONDS = 30 * 60          # 30 min idle → home


# ------------------------------------------------------------------
# EMAIL DELIVERY
# ------------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'garethzuma28@gmail.com'
EMAIL_HOST_PASSWORD = 'CHANGE_ME'
DEFAULT_FROM_EMAIL = 'garethzuma28@gmail.com'
ADMIN_REPORT_EMAIL = 'zumagareth28@gmail.com'
SITE_URL = 'http://10.20.34.172:8000'

# Brevo HTTPS channel (port 443)
BREVO_API_KEY = 'CHANGE_ME'
BREVO_SENDER_EMAIL = 'garethzuma28@gmail.com'


# ------------------------------------------------------------------
# AUTH REDIRECTS
# ------------------------------------------------------------------

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# ------------------------------------------------------------------
# DJANGO REST FRAMEWORK
# ------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'UNAUTHENTICATED_USER': None,
}


# ------------------------------------------------------------------
# CORS + CSRF + PROXY (React SPA support)
# ------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://smartq-project-gamma.vercel.app',
    'https://smartq-project-git-main-txlegend28.vercel.app',
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://smartq-project-gamma.vercel.app',
    'https://smartq-project-git-main-txlegend28.vercel.app',
    'https://antibody-refill-jugular.ngrok-free.dev',
]

# Trust ngrok's HTTPS termination
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Cross-site cookies (Vercel frontend ↔ ngrok backend = different domains)
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False   # React needs to read csrftoken for POST


# ------------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------------

class _SkipPollingFilter:
    _PREFIXES = ('/notifications/api/', '/staff/api/', '/queue/api/', '/board/api/')

    def filter(self, record):
        msg = record.getMessage()
        return not (any(p in msg for p in self._PREFIXES) and '" 200 ' in msg)


class _SmartQServerFormatter(logging.Formatter):
    GREEN = '\033[32m'
    RED = '\033[31m'
    YELLOW = '\033[33m'
    RESET = '\033[0m'
    AUTH_PATHS = ('/login/', '/logout/', '/register/')

    def format(self, record):
        msg = record.getMessage()
        status = getattr(record, 'status_code', None)
        color = ''
        if status:
            if any(p in msg for p in self.AUTH_PATHS):
                color = self.GREEN
            elif status >= 500 or status == 403:
                color = self.RED
            elif status >= 400:
                color = self.YELLOW
            elif status >= 300:
                color = self.GREEN
        server_time = getattr(record, 'server_time', self.formatTime(record))
        line = f'[{server_time}] {msg}'
        return color + line + self.RESET if color else line


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'smartq.server': {'()': _SmartQServerFormatter},
    },
    'filters': {
        'skip_polling': {'()': _SkipPollingFilter},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'smartq.server',
            'filters': ['skip_polling'],
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}